Выполнение работ по ТЗ-1
paperpaperru/outline-client pull request #1
Opened 2024-02-21 19:09 UTC by LuckyProwod

Изменения, необходимые для сборки приложения и его работы через Xray

2024-02-22 09:19 UTC, sachako requested changes
Путь к tun2socks давайте переименуем

2024-02-22 09:19 UTC, sachako commented on third_party/outline-go-tun2socks/android/tun2socks.aar
откуда взялся этот aar? это ведь уже не outline-go-tun2socks. Давайте положим его в директорию, которая не будет нас путать своим названием. И заодно README туда, о том, откуда он взялся

2024-02-22 09:19 UTC, sachako commented on third_party/outline-go-tun2socks/android/tun2socks.aar
Кажется .so под разные архитектуры собираются тут
https://github.com/2dust/AndroidLibV2rayLite/blob/master/compile-tun2socks.sh или нет

2024-02-22 10:38 UTC, LuckyProwod commented on third_party/outline-go-tun2socks/android/tun2socks.aar
При первых попытках внести изменения в Outline я пытался удалить эту папку, но это приводило к ошибкам и невозможности собрать проект, поэтому я решил, что не буду его трогать, чтобы не тратить на эту отладку время, пока оно критически не мешает. Вполне возможно, что сейчас его уже действительно можно просто удалить.
Я попробую собрать проект удалив его и пару его упоминаний, но если так быстро не получится, значит, нужно будет более детально с этим разбираться.

Кажется, что скрипт, который ты скинул, действительно может собрать нам libtun2socks.so. В дальнейшем можно будет попробовать им воспользоваться

2024-02-22 11:31 UTC, LuckyProwod commented on third_party/outline-go-tun2socks/android/tun2socks.aar
Удалять tun2socks.aar на данный момент нельзя. Благодаря ему в приложении появляются классы Shadowsocks и Tun2socks, которые используются в частях кода, которые не менялись

2024-02-23 08:40 UTC, sachako approved these changes

2024-02-23 08:46 UTC, merged